### ISSUE TITLE
Distortion周りの不具合

### ISSUE THREAD

**Issue by lb-SoraEnomoto** [CyberAgentGameEntertainment/NovaShader#51]
# 概要
Distortion周りの実装で以下2つの不具合を発見しました。
- Profilerを起動した状態でPlayするとBeginSample/EndSample関連のエラーが発生する
- カメラのターゲットテクスチャのMSAAが有効な際にDistortionシェーダーが描画されない

[実行環境]
- UnityEditor 2020.3.23f1 (Windows)

# 確認方法
## Profilerエラー
![image](https://user-images.githubusercontent.com/108331527/232394269-ff646801-1ecd-40a8-9ccd-5d076f9b1a4c.png)

1. Distortion用のRenderer Featureを追加
https://github.com/CyberAgentGameEntertainment/NovaShader#add-renderer-feature
2. `Window > Analysis > Profiler` でProfilerを起動
3. Profilerを起動した状態でPlayをすると以下に類似のエラーがでる
```
Missing Profiler.EndSample (BeginSample and EndSample count must match): DistortedUvBufferPass
Previous 5 samples:
	DistortedUvBufferPass
	Gfx.SetRenderTarget
	RenderTexture.ResolveAA
	DistortedUvBufferPass
	ScriptableRenderPass.Configure
In the scope:
	DistortedUvBufferPass
	DistortedUvBufferPass
	ScriptableRenderer.Execute: UniversalRenderPipelineAsset_Renderer
	UniversalRenderPipeline.RenderSingleCamera: Main Camera
	Render Thread
```

## MSAA有効時にDistortionが描画されない
![image](https://user-images.githubusercontent.com/108331527/232393972-068d6b8c-96ff-4bba-a2c6-85fac4c1c8ca.png)

1. Demo00シーンを開く
2. UniversalRenderPipelineAssetを開き、画像赤線部をDisabled以外の値にする
3. GameView上でDistortionが描画されなくなる

# 原因
## Profilerのエラー
![image](https://user-images.githubusercontent.com/108331527/232396353-8c110f5d-d2c1-419e-9a06-c55119d9fbad.png)

- using statement の後に `ScriptableRenderContext.ExecuteCommandBuffer` を実行する

ProfilingScopeクラスはDispose時にEndSample処理を行います。
CommandBufferが引数に設定されている場合は `CommandBuffer.EndSample` が実行されるのでExecuteCommandBufferで実行してあげる必要があります。

![image](https://user-images.githubusercontent.com/108331527/232398041-372d266b-d876-47f7-abfb-7a7dc475a3fe.png)

- CommandBufferに名前を付ける際はProfilingScopeを使用しない

現在、名前付きCommandBufferとProfilingScopeを併用した際に、BeginSample/EndSampleがうまく解決されない問題があります。（以下リンク参照）
https://github.com/Unity-Technologies/Graphics/blob/master/Packages/com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs#L619

## MSAA有効時にDistortionが描画されない
#35 で修正PRがマージされているようですが、
URPのバージョンによって適用される場合と適用されない場合があるようです。

こちらのプロジェクトでデフォルトで使用されているURP10.7.0の場合、Depthテクスチャの取り方が違うようでMSAAが有効時でも `1` （MSAA無効）を設定してやる必要があるようです。

URP12.1.7の場合は現在の #35 の修正で問題ないようです。

**Comment by Haruma-K** [comment]
ご丁寧にありがとうございます！
順次確認、対応させていただきます。

**Comment by CyTakayukiKiyohara** [comment]
下記のPRにて対応いたしました。
詳細はPRをご確認ください。
https://github.com/CyberAgentGameEntertainment/NovaShader/pull/52
