### ISSUE TITLE
Add flow functionality to basemap, flowmap, and emission textures.

### ISSUE THREAD

**Issue by HCchay** [CyberAgentGameEntertainment/NovaShader#56]

**Comment by Haruma-K** [comment]
Can you not achieve what you want to do with the Targets property of the Flow Map?

**Comment by Haruma-K** [comment]
I understand but why you do not want use custom vertex streams?

**Comment by HCchay** [comment]
It's easier to use. But it's not really a necessary question, just a thought. You are more professional. We can think about it before we decide

**Comment by Haruma-K** [comment]
Thank you for your idea!
I'm being cautious about adding everything to the NOVA Shader, because it may become difficult to use. But I'm verry happy to receive ideas for improvement.

**Comment by HCchay** [comment]
This is actually a very common one. It's just that this shader your positioning is probably only used on particle systems. You can do this through custom. But what about UI effects. Is the texture ball on top of the image? Or maybe it's just a simple model. It's just not emitted by a particle system. Then the scroll of the texture is not possible. Of course it's not really necessary for a particle system. But if you think about for example the generality of the two cases that I just said. Then this may be necessary... But now there are a lot of shader features. Thank you for sharing

**Comment by HCchay** [comment]
This is actually a very common one. It's just that this shader your positioning is probably only used on particle systems. You can do this through custom. But what about UI effects. Is the texture ball on top of the image? Or maybe it's just a simple model. It's just not emitted by a particle system. Then the scroll of the texture is not possible. Of course for particle systems this is not really necessary. But if you think about for example the generality of the two cases that I just said. Then this may be necessary... But now there are a lot of shader features. Thank you for sharing

**Comment by Haruma-K** [comment]
As you mentioned, the NOVA Shader is a shader specifically designed for particle systems, and it is essential to strictly adhere to its concept to maintain its quality as a module. If you wish to extend it for purposes other than particle systems, we recommend forking it.
