### ISSUE TITLE
Fogが二重で適用されている問題

### ISSUE THREAD

**Issue by HarukaKajita** [CyberAgentGameEntertainment/NovaShader#59]
# 概要
UberUnlit、UberLit両方でMixFog関数が二回実行されているようです。
コードを確認しても、テストシーンで挙動を確認しても二重にフォグが影響していそうであることが確認できました。
NovaShaderの全容を把握しきれていないのと、考慮できていないケースなどがあるかもしれませんので、そもそも本当に問題なのかどうかの判断含めて確認して頂けると助かります。

# テスト内容
テスト用の正しい挙動のシェーダーとして以下のURPのビルトインのシェーダーと挙動の比較をしました。

- UniversalRenderPipeline/Particles/Unlit
- UniversalRenderPipeline/Particles/Lit

シーンにフォグを設定してNovaShaderを使ったパーティクルと、ビルトインのシェーダーを使ったパーティクルを並べて色の違いを比較して確認しました。
Lit系シェーダーの比較時は、色が合うように以下の変更をしました。
- Nova/Particles/LitのマテリアルのRenderSettingsをMetalicに変更
- URP/Prticles/LitのマテリアルのColorModeをColorに変更
- URP/Prticles/LitのマテリアルのReceiveShadowをオフに変更
- シーンのDirectionalLightを削除
- シーンのEnvironmentLightingとEnvironmentReflectionのIntensityMultiplyerを0に変更
（もしかしたら他にも変更した箇所あったかもしれませんが、分かっている範囲では上記のものだけです。）

# コードの該当箇所
## Unlit
フラグメントシェーダーから呼ばれている、fragUnlit関数内でMixFogが実行され、その後フラグメントシェーダーの最後にもMixFogが実行されています。

https://github.com/CyberAgentGameEntertainment/NovaShader/blob/e4757a29799161a59392d7a521ea2b1303956c64/Assets/Nova/Runtime/Core/Shaders/ParticlesUberUnlitForward.hlsl#L33-L44

fragUnlit関数内のMixFog関数実行部分は以下の行です。
https://github.com/CyberAgentGameEntertainment/NovaShader/blob/e4757a29799161a59392d7a521ea2b1303956c64/Assets/Nova/Runtime/Core/Shaders/ParticlesUberUnlit.hlsl#L300-L305

## Lit
Unlitと同様で、fragUnlit関数内でMixFogが実行され、その後フラグメントシェーダーの最後にもMixFogが実行されています。
https://github.com/CyberAgentGameEntertainment/NovaShader/blob/e4757a29799161a59392d7a521ea2b1303956c64/Assets/Nova/Runtime/Core/Shaders/ParticlesUberLitForward.hlsl#L234-L247

# 修正について
ワークアラウンドとしては、fragUnlit関数呼び出し元で第二引数をfalseにすればテストシーンにおいては正しい挙動になることが確認できました。
最終的にはfragUnlit関数内のFogの処理を残すか、呼び出し元で実行している2回目のFogの処理を残すかの問題になると思います。

**Comment by Haruma-K** [comment]
@HarukaKajita 
ご報告ありがとうございます！
こちら対応いたしますので少々お待ちください。

**Comment by CyTakayukiKiyohara** [comment]
ご報告ありがとうございました。
こちら下記のリリースで修正いたしました。
https://github.com/CyberAgentGameEntertainment/NovaShader/releases/tag/1.5.2

**Comment by HarukaKajita** [comment]
ありがとうございます！
