### ISSUE TITLE
unity 2023バージョンでUIが崩れている

### ISSUE THREAD

**Issue by masudam0815** [CyberAgentGameEntertainment/NovaShader#61]
Unity 2023バージョンでインストールさせていただきました！ありがとうございます！
ですが開いてみると画像のように公開されているUIとは異なり（添付画像）
各項目を触っても反応しないように見受けます。

自分はデザイナーでプログラム的なことはさっぱりわからずでして…
解決方法などあればご教授いただけますと幸いです。
ご確認をお願いしたいです。

![novaシェーダー_UI](https://github.com/CyberAgentGameEntertainment/NovaShader/assets/141597394/fcb01b06-a3fb-4b36-98b0-2ed6842963f8)

[実行環境]
Unity 2023.1.7f1 (Windows)

**Comment by CyTakayukiKiyohara** [comment]
不具合のご報告ありがとうございます！
不具合を確認いたしましたところ、NovaShaderをUnity2023に対応する必要があることが分かりましたので、対応に少々お時間を頂けたらと思います。

**Comment by S20817** [comment]
2023をサポートするNovaShader2.0がリリースされましたので、最新の2.0をダウロードして確認してみてください。
こちらの環境でテストしたところ、GUI崩れの問題はありませんでした。

**Comment by masudam0815** [comment]
NovaShader2.0でGUI崩れが直っておりました！お忙しいところ対応いただいてありがとうございました！
