### ISSUE TITLE
Dissolve + Edge EmissiveでBase MapのテクスチャCompressionがHigh Qualityだと表示バグ発生

### ISSUE THREAD

**Issue by AnimaMococo** [CyberAgentGameEntertainment/NovaShader#71]
表題の件について「Base Map」テクスチャのCompression設定が「High Quality」だと、Dissolve：0で削らない状態でも全体がブロックノイズ状態で発光してしまいます。

[環境]
・Unity 2022.3.16f1 URP
・使用テクスチャアルファなし.png

[やったこと]
・Base Mapにテクスチャ設定
・Dissolve用にテクスチャ設定
・Emissive：Edgeに設定

→Dissolveは０で削らないままスポーン

CompressionがLow Quality, Normal Quality, Noneでは問題ありません
（Emissive Map以外は未確認）

![image](https://github.com/CyberAgentGameEntertainment/NovaShader/assets/95951937/84d647c7-f8f5-4872-b90c-455ae1749532)

上記意図しない設定でしょうか？（デフォルトのCompression : Normal Quality推奨など）
以上、ご教示いただけますと幸いです。

**Comment by CyTakayukiKiyohara** [comment]
不具合のご報告ありがとうございます。
こちら現在調査中となります。
少々お時間をください。

**Comment by CA-Tatami** [comment]
@AnimaMococo 
ご報告いただいた不具合を修正しました。
テクスチャ圧縮設定をHigh Qualityに指定した場合圧縮フォーマットにBC7が適用されるのですが、誤差が大きくなり意図しない判定が行われアーティファクトが発生するというものでした。
mainブランチおよびTagがバージョン2.2.2のデータに上記修正内容を反映いたしましたので、こちらからご利用いただければと思います。

この度は詳細に不具合をお知らせいただきありがとうございました。
また何か問題を見つけられましたらご報告いただいだければ幸いです。

**Comment by AnimaMococo** [comment]
@CA-Tatami 
バージョン2.2.2でテクスチャ圧縮設定をHigh Qualityの問題が解決されていることを確認できました！
非常に早くのご対応いただきありがとうございます！
